### ISSUE TITLE
ImageMagick crashes with static binary

### ISSUE THREAD

**Issue by gen2brain** [gen2brain/cbconvert#16]
When the fully static binary is compiled any IM invocation crashes in OpenPixelCache:
```
Thread 12 "cbconvert" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 335574]
0x0000000000ea38b5 in OpenPixelCache ()
(gdb) bt
#0  0x0000000000ea38b5 in OpenPixelCache ()
#1  0x000000000040726b in GetImagePixelCache ()
#2  0x0000000000408d42 in QueueAuthenticPixelCacheNexus ()
#3  0x0000000000408efe in GetAuthenticPixelCacheNexus ()
#4  0x0000000000409049 in GetAuthenticPixels ()
#5  0x00000000010eb239 in WriteOnePNGImage ()
#6  0x00000000010edfa3 in WritePNGImage ()
#7  0x0000000000ec8b92 in WriteImage ()
#8  0x0000000000e54f2c in MagickWriteImage ()
#9  0x00000000006259df in _cgo_83eb6e58db04_Cfunc_MagickWriteImage ()
#10 0x000000000046db64 in runtime.asmcgocall () at runtime/asm_amd64.s:844
#11 0x000000c0003a0060 in ?? ()
#12 0x000000c0003a0001 in ?? ()
#13 0x00007fffd0a030c8 in ?? ()
#14 0x00007fffd08fc9f0 in ?? ()
#15 0x0000000000423ba5 in runtime.SetFinalizer.func1 () at runtime/mfinal.go:401
#16 0x000000000046bce9 in runtime.systemstack () at runtime/asm_amd64.s:492
#17 0x00000000019d6bd0 in ?? ()
#18 0x0000000000020000 in ?? ()
#19 0x0000000000000000 in ?? ()
(gdb) 

```

There are no issues with shared ImageMagick/MagickWand.

**Comment by gen2brain** [comment]
Crashes happen only with musl, there are no issues with Glibc https://github.com/ImageMagick/ImageMagick/issues/5964. The Linux static binary is now built with the Glibc toolchain.
